module Decor_Standards
	def self.get_attr_value()
		@model = Sketchup.active_model
		@selection = @model.selection[0]

		@get_vsides = DP::get_visible_sides @selection
		# puts "@get_vsides-----#{@get_vsides}"

		@show = 0
		if @selection.nil?
			UI.messagebox 'Component not selected!', MB_OK
			@show = 1
		elsif Sketchup.active_model.selection[1] != nil then
			UI.messagebox 'More than one component selected!', MB_OK
			@show = 1
		end
		
		if @show == 0
			@dict_name = 'carcase_spec'
			rawmat = @selection.get_attribute(@dict_name, 'attr_raw_material')
			rawmat = "" if rawmat.nil?
			
			if @get_vsides[0] == true
				lam_left = @selection.get_attribute(@dict_name, 'left_lam_value')
				lam_left = "" if lam_left.nil?
				left_laminate = 1
			end

			if @get_vsides[1] == true
				lam_right = @selection.get_attribute(@dict_name, 'right_lam_value')
				lam_right = "" if lam_right.nil?
				right_laminate = 1
			end

			if @get_vsides[2] == true
				lam_top = @selection.get_attribute(@dict_name, 'top_lam_value')
				lam_top = "" if lam_top.nil?
				top_laminate = 1
			end

			hand = @selection.get_attribute(@dict_name, 'attr_handles_type')
			hand = "" if hand.nil?

			softcl = @selection.get_attribute(@dict_name, 'attr_soft_close')
			softcl = "" if softcl.nil?

			fintyp = @selection.get_attribute(@dict_name, 'attr_finish_type')
			fintyp = "" if fintyp.nil?

			shutfin = @selection.get_attribute(@dict_name, 'attr_shutter_finish')
			shutfin = "" if shutfin.nil?

			intfin = @selection.get_attribute(@dict_name, 'attr_internal_finish')
			intfin = "" if intfin.nil?

			# defcode = @selection.definition.name
			defcode = @selection.get_attribute(@dict_name, 'attr_product_code')

			defname = @selection.definition.get_attribute(@dict_name, 'attr_product_name')
			if !defname.nil?
				defname = defname.gsub("_", " ")
			else
				defname = @selection.get_attribute(@dict_name, 'attr_product_name')
				defname = "" if defname.nil?
			end
			
			mainarr = []
			mainarr.push("attr_raw_material|"+rawmat)
            mainarr.push("attr_handles_type|"+hand)
            mainarr.push("attr_soft_close|"+softcl)
            mainarr.push("attr_finish_type|"+fintyp)
			mainarr.push("attr_product_code|"+defcode)
			mainarr.push("attr_product_name|"+defname)
			mainarr.push("attr_shutter_finish|"+shutfin)
			if defname.include?("Sliding") || defname.include?("sliding")
				mainarr.push("attr_internal_finish|"+intfin)
			end

		  if left_laminate == 1
		  	mainarr.push("left_lam_value|"+lam_left)
		  end

		  if right_laminate == 1
		  	mainarr.push("right_lam_value|"+lam_right)
		  end

		  if top_laminate == 1
		  	mainarr.push("top_lam_value|"+lam_top)
		  end
			return mainarr
		end
	end

	def self.update_attr(b)
		@dict_name = 'carcase_spec'
		comp = Sketchup.active_model.selection[0]
		inph =	JSON.parse(b)
		puts "update_attr : #{inph}"
		inph.each{|k, v|
			if v.is_a?(Array)
				for i in v
					instance    = LAM::add_laminate comp, i
					comp        = instance
				end
			else
				@selection.set_attribute(@dict_name, k, v) if @selection && !@selection.deleted?
			end
		}
		return 1
	end

	def self.uptdetail()
		newarr = []
		cliname = Sketchup.active_model.get_attribute(:rio_global, 'client_name')
		cliname = "" if cliname.nil?
		proname = Sketchup.active_model.get_attribute(:rio_global, 'project_name')
		proname = "" if proname.nil?
		cliid = Sketchup.active_model.get_attribute(:rio_global, 'client_id')
		cliid = "" if cliid.nil?
		aptname = Sketchup.active_model.get_attribute(:rio_global, 'apartment_name')
		aptname = "" if aptname.nil?
		desname = Sketchup.active_model.get_attribute(:rio_global, 'designer_name')
		desname = "" if desname.nil?
		flatno = Sketchup.active_model.get_attribute(:rio_global, 'flat_number')
		flatno = "" if flatno.nil?
		prono = Sketchup.active_model.get_attribute(:rio_global, 'project_number')
		prono = "" if prono.nil?
		visname = Sketchup.active_model.get_attribute(:rio_global, 'visualizer_name')
		visname = "" if visname.nil?

		newarr.push("client_name|"+cliname)
		newarr.push("project_name|"+proname)
		newarr.push("client_id|"+cliid)
		newarr.push("apartment_name|"+aptname)
		newarr.push("designer_name|"+desname)
		newarr.push("flat_number|"+flatno)
		newarr.push("project_number|"+prono)
		newarr.push("visualizer_name|"+visname)

		return newarr
	end

	def self.get_laminate_cat
		path = RIO_ROOT_PATH + "/materials/"
		dirpath = Dir[path+"*"]
		mainarray = ""
		dirpath.each {|mc|
			lval = mc.split("/").last
			lam = lval.gsub("-", " ")
			mainarray += '<option value="'+lval+'">'+lam+'</option>'
		}
		lastarray = '<select class="ui dropdown" id="lam-category" onchange="changeLaminate(this.value)"><option value="0">Select...</option>'+mainarray+'</select>'
		return lastarray
	end

	def self.get_laminate_img(input)
		path = RIO_ROOT_PATH + "/materials/" + input + "/"
		dirpath = Dir[path+"*"]
		count = []
		dival = ""
		path_length = (dirpath.length/4)+1
		path_length.times{|index|
			images_arr = dirpath.shift(4)
			lam1 = images_arr[0].split("/").last if !images_arr[0].nil?
			lam1val = lam1.gsub(".jpg", "").gsub(".JPG", "") if !lam1.nil?
			lam2 = images_arr[1].split("/").last if !images_arr[1].nil?
			lam2val = lam2.gsub(".jpg", "").gsub(".JPG", "") if !lam2.nil?
			lam3 = images_arr[2].split("/").last if !images_arr[2].nil?
			lam3val = lam3.gsub(".jpg", "").gsub(".JPG", "") if !lam3.nil?
			lam4 = images_arr[3].split("/").last if !images_arr[3].nil?
			lam4val = lam4.gsub(".jpg", "").gsub(".JPG", "") if !lam4.nil?

			dival += '<div class="ui equal width grid">'
			dival += '<div class="column"><div class="lam_name">'+lam1val+'</div><div class="lam_img"><img src="'+images_arr[0]+'" onclick="getImgSrc(this)"></div></div>' if !images_arr[0].nil?
			dival += '<div class="column"><div class="lam_name">'+lam2val+'</div><div class="lam_img"><img src="'+images_arr[1]+'" onclick="getImgSrc(this)"></div></div>' if !images_arr[1].nil?
			dival += '<div class="column"><div class="lam_name">'+lam3val+'</div><div class="lam_img"><img src="'+images_arr[2]+'" onclick="getImgSrc(this)"></div></div>' if !images_arr[2].nil?
			dival += '<div class="column"><div class="lam_name">'+lam4val+'</div><div class="lam_img"><img src="'+images_arr[3]+'" onclick="getImgSrc(this)"></div></div>' if !images_arr[3].nil?
			dival += '</div>'
		}
		return dival
	end
end